version: 2.0
jobs:
  build:
    docker:
      - image: typelead/eta:latest
    steps:
    - checkout

    - restore_cache:
        key: wai-servlet-cache-v1-

    - run: etlas update

    - run: etlas build

    - save_cache:
        key: wai-servlet-cache-v1-{{ epoch }}
        paths:
          - "~/.etlas/config"
          - "~/.etlas/packages"
          - "~/.etlas/tools"
          - "~/.coursier"

workflows:
  version: 2
  full_cycle:
    jobs:
      - build
      
